openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts-app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: Documentation for working with a collection of contacts
tags:
  - name: Contacts
    description: Operations about contacts
servers:
  - url: http://localhost:3000
  - url: https://contacts-app-swagger-3d9a.onrender.com
paths:
  /contacts/{id}:
    get:
      $ref: ../swagger/paths/contacts/{id}/get.yaml
    patch:
      $ref: ../swagger/paths/contacts/patch.yaml
    delete:
      $ref: ../swagger/paths/contacts/delete.yaml
  /contacts:
    get:
      $ref: ../swagger/paths/contacts/get.yaml
    post:
      $ref: ../swagger/paths/contacts/post.yaml

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
